version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "analysis-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1whh6mxizo8nn"
s3_prefix = "analysis-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

